---

- hosts: all
  become: true
  tasks:

  - name: install apache and php package
    package:
      update_cache: yes
      name:
        - "{{ apache package }}"
        - "{{ php package }}"
      state: latest
